# Generated by Django 5.1.2 on 2024-10-24 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_member_otp_setup_complete_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='otp_setup_complete',
        ),
    ]
